export const addInv = {
  searchInput: '#searchInput',
  suggestionList: '#asset-suggestion-list',
  suggestionItems: '#asset-suggestion-list li',
  amount: '#amount',
  unitPrice: '#unitPrice',
  totalSpend: '#totalSpend',
  typeReadOnly: 'input[placeholder="Select an asset"]',
  submitBtn: 'form .btn.btn-primary',
  cancelBtn: 'form .btn.btn-negative',
  errorMsg: '.text-red-500.mb-4.text-center, [role="alert"]',
  modal: '.fixed.inset-0 .card',
  modalConfirmBtn: '.fixed.inset-0 .btn.btn-primary',
  modalCancelBtn: '.fixed.inset-0 .btn.btn-negative',
};
