version: '3.8'

services:
  react:
    build:
      context: ./wtf-react
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://node:5000
    image: registry.gitlab.com/wealth-tracking-framework/wealth-tracking-framework/wtf-react:latest
    container_name: wtf-react
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    networks:
      - wtfnet
    depends_on:
      node:
        condition: service_healthy
    mem_limit: 1.5g
    mem_reservation: 1g

  node:
    image: registry.gitlab.com/wealth-tracking-framework/wealth-tracking-framework/wtf-node:latest
    container_name: wtf-node
    ports:
      - "4000:5000"
    env_file:
      - .env
    networks:
      - wtfnet
    mem_limit: 1.5g
    mem_reservation: 1g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:15
    container_name: wtf-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${PGUSER}"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - wtfnet

volumes:
  postgres_data:

networks:
  wtfnet:
    name: wtfnet
    driver: bridge
