services:
  wtf-nginx:
    image: nginx:alpine
    container_name: wtf-nginx
    volumes:
      - ./wtf-nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - wtf-react-build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wtf-react
      - wtf-node
      - wtf-jenkins
    networks:
      - wtfnet

  wtf-react:
    build:
      context: ./wtf-react
    image: registry.gitlab.com/wealth-tracking-framework/wealth-tracking-framework/wtf-react:latest
    container_name: wtf-react
    volumes:
      - wtf-react-build:/build
    networks:
      - wtfnet
    depends_on:
      wtf-node:
        condition: service_healthy

  wtf-node:
    build:
      context: ./wtf-node
    image: registry.gitlab.com/wealth-tracking-framework/wealth-tracking-framework/wtf-node:latest
    container_name: wtf-node
    env_file:
      - .env
    networks:
      - wtfnet
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  wtf-finnhub:
    build:
      context: ./wtf-finnhub
    image: registry.gitlab.com/wealth-tracking-framework/wealth-tracking-framework/wtf-finnhub:latest
    container_name: wtf-finnhub
    env_file:
      - .env
    networks:
      - wtfnet
    depends_on:
      - wtf-node
      - postgres

  wtf-coingecko:
    build:
      context: ./wtf-coingecko
    image: registry.gitlab.com/wealth-tracking-framework/wealth-tracking-framework/wtf-coingecko:latest
    container_name: wtf-coingecko
    env_file:
      - .env
    networks:
      - wtfnet
    depends_on:
      - wtf-node
      - postgres

  wtf-jenkins:
    build:
      context: ./wtf-jenkins
    image: registry.gitlab.com/wealth-tracking-framework/wealth-tracking-framework/wtf-jenkins:latest
    container_name: wtf-jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - wtfnet

  postgres:
    image: postgres:15
    container_name: wtf-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wtfnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${PGUSER}"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  jenkins_data:
  wtf-react-build:
    external: true

networks:
  wtfnet:
    driver: bridge
