- hosts: all
  become: yes
  tasks:
    - name: Ensure wtf-nginx directory exists
      file:
        path: /opt/wealth-tracking-framework/wtf-nginx
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Check if nginx.conf exists and whether it's a dir
      stat:
        path: /opt/wealth-tracking-framework/wtf-nginx/nginx.conf
      register: ansible_stat_nginxconf

    - name: Remove incorrect nginx.conf directory if it exists
      file:
        path: /opt/wealth-tracking-framework/wtf-nginx/nginx.conf
        state: absent
      when: ansible_stat_nginxconf.stat.exists and ansible_stat_nginxconf.stat.isdir

    - name: Copy correct nginx.conf file
      copy:
        src: "{{ playbook_dir }}/../nginx.conf"
        dest: /opt/wealth-tracking-framework/nginx.conf
        owner: root
        group: root
        mode: '0644'

    - name: Deploy Jenkins with Docker Compose
      shell: |
        cd /opt/wealth-tracking-framework
        docker compose down --remove-orphans
        docker compose up -d --build
