- hosts: all
  become: yes
  tasks:
    - name: Copy Jenkins NGINX config
      copy:
        src: ../wtf-jenkins/jenkins.conf
        dest: /etc/nginx/sites-available/jenkins.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable Jenkins site
      file:
        src: /etc/nginx/sites-available/jenkins.conf
        dest: /etc/nginx/sites-enabled/jenkins.conf
        state: link
        force: yes

    - name: Remove default site if present
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Test NGINX config
      command: nginx -t

    - name: Reload NGINX
      service:
        name: nginx
        state: reloaded
