- name: Deploy WTF project on Ubuntu server
  hosts: all
  become: yes
  vars_files:
    - secrets.yml

  vars:
    project_dir: /opt/wealth-tracking-framework
    artifactory_registry: "registry.gitlab.com/wealth-tracking-framework/wealth-tracking-framework"
    react_build_volume: "wtf-react-build"

  tasks:
    - name: Fail if not running on Ubuntu
      fail:
        msg: "This playbook only supports Ubuntu. Detected {{ ansible_distribution }} {{ ansible_distribution_version }}."
      when: ansible_distribution != "Ubuntu"

    - name: Stop all running containers
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        state: absent

    - name: Remove any containers from previous runs (ignore errors)
      shell: |
        docker rm -f wtf-node wtf-react wtf-nginx wtf-postgres wtf-coingecko wtf-finnhub wtf-certbot-renew wtf-jenkins || true
      ignore_errors: true

    - name: Remove wtf-react-build volume
      community.docker.docker_volume:
        name: "{{ react_build_volume }}"
        state: absent

    - name: Remove React and NGINX images
      community.docker.docker_image:
        name: "{{ item }}"
        state: absent
      loop:
        - registry.gitlab.com/wealth-tracking-framework/wealth-tracking-framework/wtf-react:latest
        - nginx:alpine
      ignore_errors: true

    - name: Log into GitLab Container Registry using Vault secrets
      community.docker.docker_login:
        registry_url: "{{ artifactory_registry }}"
        username: "{{ gitlab_user }}"
        password: "{{ gitlab_token }}"

    - name: Ensure wtf-react-build volume exists
      community.docker.docker_volume:
        name: "{{ react_build_volume }}"
        state: present

    - name: Ensure wtfnet Docker network exists
      community.docker.docker_network:
        name: wtfnet
        state: present
        driver: bridge

    - name: Deploy all WTF services including Jenkins
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        pull: "always"
        state: present
        build: "never"

    - name: Run database migrations inside node container
      shell: docker exec wtf-node npm run migrate
      register: migrate_result
      retries: 5
      delay: 5
      until: migrate_result.rc == 0

    - name: Restart CoinGecko fetcher
      shell: docker compose restart wtf-coingecko
      args:
        chdir: "{{ project_dir }}"

    - name: Restart Finnhub fetcher
      shell: docker compose restart wtf-finnhub
      args:
        chdir: "{{ project_dir }}"

    - name: Set permissions for React build directory
      file:
        path: "{{ project_dir }}/wtf-react/build"
        mode: '0755'
        recurse: yes

    - name: Confirm deployment success message
      debug:
        msg: "WTF project deployed successfully on {{ inventory_hostname }}"