- name: Deploy WTF project on Ubuntu server
  hosts: all
  become: yes
  vars_files:
    - secrets.yml

  vars:
    project_dir: /opt/wealth-tracking-framework
    artifactory_registry: "registry.gitlab.com/wealth-tracking-framework/wealth-tracking-framework"
    react_build_volume: "wtf-react-build"

  tasks:
    - name: Fail if not running on Ubuntu
      fail:
        msg: "This playbook only supports Ubuntu. Detected {{ ansible_distribution }} {{ ansible_distribution_version }}."
      when: ansible_distribution != "Ubuntu"

    - name: Stop React and NGINX containers (if running)
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        services:
          - wtf-react
          - wtf-nginx
        state: absent
      ignore_errors: true

    - name: Remove wtf-react-build volume
      community.docker.docker_volume:
        name: "{{ react_build_volume }}"
        state: absent

    - name: Remove React and NGINX images
      community.docker.docker_image:
        name: "{{ item }}"
        state: absent
      loop:
        - registry.gitlab.com/wealth-tracking-framework/wealth-tracking-framework/wtf-react:latest
        - nginx:alpine
      ignore_errors: true

    - name: Log into GitLab Container Registry using Vault secrets
      community.docker.docker_login:
        registry_url: "{{ artifactory_registry }}"
        username: "{{ gitlab_user }}"
        password: "{{ gitlab_token }}"

    - name: Ensure wtf-react-build volume exists
      community.docker.docker_volume:
        name: "{{ react_build_volume }}"
        state: present

    - name: Pull latest images from GitLab Registry
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        pull: "always"
      register: pull_result
      failed_when: pull_result.failed

    - name: Stop running containers (ignore errors if none)
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        state: absent
      ignore_errors: true

    - name: Start all services without building
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        state: present
        build: "never"
      register: up_result
      failed_when: up_result.failed

    - name: Run database migrations inside node container
      shell: docker exec wtf-node npm run migrate
      register: migrate_result
      retries: 5
      delay: 5
      until: migrate_result.rc == 0

    - name: Restart CoinGecko fetcher
      shell: docker compose restart wtf-coingecko
      args:
        chdir: "{{ project_dir }}"

    - name: Restart Finnhub fetcher
      shell: docker compose restart wtf-finnhub
      args:
        chdir: "{{ project_dir }}"

    - name: Set permissions for React build directory
      file:
        path: "{{ project_dir }}/wtf-react/build"
        mode: '0755'
        recurse: yes

    - name: Reload NGINX after obtaining certs
      shell: docker compose exec wtf-nginx nginx -s reload
      args:
        chdir: "{{ project_dir }}"

    - name: Confirm deployment success message
      debug:
        msg: "WTF project deployed successfully on {{ inventory_hostname }}"