pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('react-ui') {
          sh 'npm install'
        }
        dir('node-api') {
          sh 'npm install'
        }
      }
    }

    stage('Run Cypress Tests') {
      steps {
        dir('cypress-tests') {
          sh 'npm install'
          sh 'npx cypress run'
        }
      }
    }

    stage('Generate Allure Report') {
      steps {
        sh 'npx allure generate cypress-tests/allure-results --clean -o allure-report'
      }
    }
  }
}
