FROM node:20

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
ENV CHOKIDAR_USEPOLLING=true
ENV HOST=0.0.0.0
ENV DANGEROUSLY_DISABLE_HOST_CHECK=true

EXPOSE 3000
CMD ["npm", "start"]
