- name: Build and start WTF services
  hosts: localhost
  become: false

  tasks:
    - name: Build all Docker Compose services
      shell: docker compose build
      args:
        chdir: "{{ playbook_dir }}/.."

    - name: Start core services (PostgreSQL, Adminer, Node API, React UI, Jenkins, Allure)
      shell: docker compose up -d postgres adminer node-api react-ui jenkins allure
      args:
        chdir: "{{ playbook_dir }}/.."

    - name: Run database migrations inside node-api container
      shell: docker exec wtf-api npm run migrate -- up
      args:
        chdir: "{{ playbook_dir }}/.."

    - name: Open Postgres API check in browser (macOS only)
      shell: open http://localhost:4000/api/db-check
      when: ansible_os_family == "Darwin"

    - name: Open Adminer in browser (macOS only)
      shell: open http://localhost:8081
      when: ansible_os_family == "Darwin"

    - name: Open React UI in browser (macOS only)
      shell: open http://localhost:3000
      when: ansible_os_family == "Darwin"

    - name: Open Node API test route in browser (macOS only)
      shell: open http://localhost:4000/api/test
      when: ansible_os_family == "Darwin"

    - name: Open Jenkins in browser (macOS only)
      shell: open http://localhost:8080
      when: ansible_os_family == "Darwin"

    - name: Open Allure in browser (macOS only)
      shell: open http://localhost:5050
      when: ansible_os_family == "Darwin"
